sample_statistics:
  N: 100
  T: 1000
  left_support: 0.0
  right_support: 1.0
  mean: 0.5
  stdev: 0.1
  bound: both
  confidence: 0.95
  statistic: mean
  seed: 100
  distribution: "beta"
plot_configs:
  err_style: "ci_bars"
  interpolate: True
  percentile: 95
uniform:
  left_support: 0.0
  right_support: 1.0
  true_mean: 0.5
normal:
  left_support: 0.0
  right_support: 1.0
  true_mean: 0.5
  scale: 0.1
exponential:
  loc: 0.0
  scale: 0.1
  true_mean: 0.1
data_processing_details:
  process_mean: True
  process_var: False
  process_percentiles: False
  process_ts: False
  percentiles: [95]
