sample_statistics:
  N: 100
  T: 1000
  left_support: 0.0
  right_support: 1.0
  mean: 0.5
  stdev: 0.1
  bound: both
  confidence: 0.95
  statistic: mean
  seed: 100
  distribution: "uniform"
plot_configs:
  err_style: "ci_bars"
  interpolate: True
  percentile: 95
  color_type: "same bound"
data_processing_details:
  process_mean: True
  process_var: False
  process_percentiles: True
  process_ts: False
  percentiles: [15]
