sample_statistics:
  N: 100
  T: 10
  left_support: 0.0
  right_support: 1.0
  mean: 0.5
  stdev: 0.1
  seed: 100
  distribution: "exponential"
plot_configs:
  err_style: "ci_bars"
  interpolate: True